#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=4:00:00
#PBS -N AFQ_no-life
#PBS -V

module load matlab
module load spm

rm -rf tracts
rm -f finished

echo "starting matlab"
matlab -nodisplay -nosplash -r main
if [ ! -s output.mat ];
then
	echo "output missing"
	exit 1
fi
